---
defaultServer: https://example.com/frontend
defaultLanguage: ru
languages:
  ru: Русский
  en: English
modules:
- asterisk
- addresses
- queues
- about
- darkmode
asterisk:
  ws: wss://example.com/wss
  ice:
  - urls:
    - stun:stun.l.google.com:19302
  sipDomain: "<!-- your asterisk server external ip here -->"
map:
  tile: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  crs: EPSG3857
  default:
    lat: 51.505
    lon: -0.09
    zoom: 13
  min: 4
  max: 18
regExp:
  phone: "^(7 \(\d{3}\) \d{3}-\d{2}-\d{2}|7\d{10})$"
  rfid: "^[0-9A-F]{14}$"
defaultRoute: "#about"
logo: rbt
phonePattern: '7 (###) ###-##-##'
printServer: https://example.com/print
