<?php

return [
    0 => ['eCount' => 8, 'dCount' => 0, 'switchCount' => 1, 'unitStart' => 0],
    1 => ['eCount' => 10, 'dCount' => 0, 'switchCount' => 1, 'unitStart' => 0],
    2 => ['eCount' => 10, 'dCount' => 0, 'switchCount' => 1, 'unitStart' => 0],
    3 => ['eCount' => 10, 'dCount' => 0, 'switchCount' => 1, 'unitStart' => 1],
    4 => ['eCount' => 10, 'dCount' => 0, 'switchCount' => 1, 'unitStart' => 0],
    6 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 8, 'unitStart' => 0],
    7 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 1, 'unitStart' => 0],
    8 => ['eCount' => 26, 'dCount' => 10, 'switchCount' => 1, 'unitStart' => 0],
    9 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 1, 'unitStart' => 0],
    10 => ['eCount' => 10, 'dCount' => 0, 'switchCount' => 1, 'unitStart' => 0],
    11 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 5, 'unitStart' => 0],
    12 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 8, 'unitStart' => 0],
    13 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 1, 'unitStart' => 0],
    20 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 1, 'unitStart' => 0],
    30 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 1, 'unitStart' => 0],
    40 => ['eCount' => 15, 'dCount' => 17, 'switchCount' => 1, 'unitStart' => 0],
    50 => ['eCount' => 4, 'dCount' => 1, 'switchCount' => 1, 'unitStart' => 0],
    51 => ['eCount' => 10, 'dCount' => 1, 'switchCount' => 1, 'unitStart' => 0],
    52 => ['eCount' => 10, 'dCount' => 10, 'switchCount' => 1, 'unitStart' => 0],
    60 => ['eCount' => 10, 'dCount' => 8, 'switchCount' => 1, 'unitStart' => 1],
    61 => ['eCount' => 10, 'dCount' => 8, 'switchCount' => 1, 'unitStart' => 1],
    62 => ['eCount' => 10, 'dCount' => 8, 'switchCount' => 1, 'unitStart' => 1],
    63 => ['eCount' => 10, 'dCount' => 16, 'switchCount' => 1, 'unitStart' => 1],
    64 => ['eCount' => 10, 'dCount' => 16, 'switchCount' => 1, 'unitStart' => 1],
    65 => ['eCount' => 10, 'dCount' => 22, 'switchCount' => 1, 'unitStart' => 1],
    66 => ['eCount' => 10, 'dCount' => 22, 'switchCount' => 1, 'unitStart' => 1],
];
