CREATE TABLE vars (var_id integer not null primary key autoincrement, var_name text not null, var_value text);
CREATE INDEX vars_id on vars(var_id);
CREATE INDEX vars_var_name on vars(var_name);
INSERT INTO vars (var_name, var_value) values ('dbVersion', '0');
CREATE TABLE users (uid integer not null primary key autoincrement, login text not null, password text not null, enabled integer, real_name text, e_mail text, phone text);
CREATE UNIQUE INDEX users_login on users(login);
CREATE INDEX users_real_name on users(real_name);
CREATE UNIQUE INDEX users_e_mail on users(e_mail);
CREATE INDEX users_phone on users(phone);
CREATE TABLE groups (gid integer not null primary key autoincrement, acronym text not null, name text not null);
CREATE UNIQUE INDEX groups_acronym on groups(acronym);
CREATE UNIQUE INDEX groups_name on groups(name);
CREATE TABLE users_groups (uid integer, gid integer);
CREATE INDEX users_groups_uid on users_groups(uid);
CREATE INDEX users_groups_gid on users_groups(gid);
CREATE UNIQUE INDEX users_groups_uid_gid on users_groups(uid, gid);
CREATE TABLE api_methods(aid text not null primary key, api text not null, method text not null, request_method text not null);
CREATE UNIQUE INDEX api_methods_uniq on api_methods(api, method, request_method);
CREATE TABLE users_rights(uid integer not null, aid text not null, allow integer);
CREATE UNIQUE INDEX users_rights_uniq on users_rights(uid, aid);
CREATE TABLE groups_rights(gid integer not null, aid text not null, allow integer);
CREATE UNIQUE INDEX groups_rights_uniq on groups_rights(gid, aid);
CREATE TABLE api_methods_common(aid text not null primary key);
CREATE TABLE api_methods_personal(aid text not null primary key);
