CREATE TABLE address_buildings (bid integer not null primary key autoincrement, address text not null, guid text);
CREATE UNIQUE INDEX address_buildings_guid on address_buildings(guid);
CREATE UNIQUE INDEX address_buildings_address on address_buildings(address);
CREATE TABLE address_entrances (eid integer not null primary key autoincrement, bid integer not null, entrance text not null);
CREATE INDEX address_entrances_bid on address_entrances(bid);
CREATE UNIQUE INDEX address_entrances_bid_entrance on address_entrances(bid, entrance);
CREATE TABLE address_flats (fid integer not null primary key autoincrement, eid integer not null, flat_number integer, floor integer);
CREATE INDEX address_flats_eid on address_flats(eid);
CREATE INDEX address_flats_floor on address_flats(floor);
CREATE UNIQUE INDEX address_flats_flat_number on address_flats(flat_number);