<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit844c78dded60e2246a8b4ad78746ac39
{
    public static $files = array (
        'a4a119a56e50fbb293281d9a48007e0e' => __DIR__ . '/..' . '/symfony/bootstrap.php',
        '3a37ebac017bc098e9a86b35401e7a68' => __DIR__ . '/..' . '/mongodb/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Php80\\' => 23,
        ),
        'M' => 
        array (
            'MongoDB\\' => 8,
        ),
        'J' => 
        array (
            'Jean85\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Php80\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony',
        ),
        'MongoDB\\' => 
        array (
            0 => __DIR__ . '/..' . '/mongodb',
        ),
        'Jean85\\' => 
        array (
            0 => __DIR__ . '/..' . '/jean85',
        ),
    );

    public static $classMap = array (
        'Attribute' => __DIR__ . '/..' . '/symfony/Resources/stubs/Attribute.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'PhpToken' => __DIR__ . '/..' . '/symfony/Resources/stubs/PhpToken.php',
        'Stringable' => __DIR__ . '/..' . '/symfony/esources/stubs/Stringable.php',
        'UnhandledMatchError' => __DIR__ . '/..' . '/symfony/Resources/stubs/UnhandledMatchError.php',
        'ValueError' => __DIR__ . '/..' . '/symfony/Resources/stubs/ValueError.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit844c78dded60e2246a8b4ad78746ac39::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit844c78dded60e2246a8b4ad78746ac39::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit844c78dded60e2246a8b4ad78746ac39::$classMap;

        }, null, ClassLoader::class);
    }
}
