#!/usr/bin/expect -f

set timeout 5

set server [lindex $argv 0]
set login [lindex $argv 1]
set password [lindex $argv 2]
set config [lindex $argv 3]

spawn telnet $server

expect "ogin:" {send "$login\r"}

expect "assword:" {send "$password\r"}

expect "<~>"
send "echo '$config' > /etc/rsyslogd/custom.conf && /etc/init.d/S01rsyslogd restart\r"

expect "<~>"
send "exit\r"
