<?php

namespace hw\ip\domophone\akuvox\Entities;

use InvalidArgumentException;

final class Dialplan extends AbstractEntity
{
    protected static array $apiParamMap = [
        'ID' => 'id',
        'Line' => 'line',
        'Prefix' => 'prefix',
        'Replace1' => 'replace1',
        'Replace2' => 'replace2',
        'Replace3' => 'replace3',
        'Replace4' => 'replace4',
        'Replace5' => 'replace5',
    ];

    public string $id = '-1'; // Autogenerated by the device upon creation a new one
    public string $prefix;
    public string $line = '0';
    public string $replace1 = '';
    public string $replace2 = '';
    public string $replace3 = '';
    public string $replace4 = '';
    public string $replace5 = '';

    /**
     * Creates a new `Dialplan` instance.
     *
     * @param string $prefix Unique prefix.
     * @throws InvalidArgumentException if `$prefix` is empty.
     */
    public function __construct(string $prefix)
    {
        if (empty($prefix)) {
            throw new InvalidArgumentException('Prefix cannot be empty');
        }

        $this->prefix = $prefix;
    }

    protected static function getRequiredField(): string
    {
        return 'Prefix';
    }
}
