<?php

namespace hw\ip\domophone\akuvox\Entities;

use InvalidArgumentException;

final class Group extends AbstractEntity
{
    protected static array $apiParamMap = [
        'ID' => 'id',
        'Name' => 'name',
        'Number' => 'number',
    ];

    public string $id = '-1'; // Autogenerated by the device upon creation a new one
    public string $name;
    public string $number = '';

    /**
     * Creates a new `Group` instance.
     *
     * @param string $name Unique group name.
     * @throws InvalidArgumentException if `$name` is empty.
     */
    public function __construct(string $name)
    {
        if (empty($name)) {
            throw new InvalidArgumentException('Group name cannot be empty');
        }

        $this->name = $name;
    }

    protected static function getRequiredField(): string
    {
        return 'Name';
    }
}
