<?php

namespace hw\ip\domophone\akuvox\Entities;

use InvalidArgumentException;

/**
 * Represents a user in the Akuvox intercom.
 */
final class User extends AbstractEntity
{
    protected static array $apiParamMap = [
        'ID' => 'id',
        'UserID' => 'userId',
        'DoorNum' => 'doorNum',
        'PrivatePIN' => 'privatePin',
        'LiftFloorNum' => 'liftFloorNum',
        'Name' => 'name',
        'Schedule' => 'schedule',
        'CardCode' => 'cardCode',
        'WebRelay' => 'webRelay',
        'C4Event' => 'c4Event',
        'PriorityCall' => 'priorityCall',
        'DialAccount' => 'dialAccount',
        'PhoneNum' => 'phoneNum',
        'AnalogSystem' => 'analogSystem',
        'AnalogNumber' => 'analogNumber',
        'AnalogReplace' => 'analogReplace',
        'AnalogMode' => 'analogMode',
        'AnalogProxyAddress' => 'analogProxyAddress',
        'ContactID' => 'contactId',
        'Group' => 'group',
        'BLEAuthCode' => 'bleAuthCode',
        'BLE_KEY_ID' => 'bleKeyId',
        'BLE_Expired' => 'bleExpired',
        'BLE_Status' => 'bleStatus',
        'Source' => 'source',
        'Schedule-Relay' => 'scheduleRelay',
        'QrCodeUrl' => 'qrCodeUrl',
    ];

    public string $id = '-1'; // Autogenerated by the device upon creation a new one
    public string $userId;
    public string $doorNum = '0';
    public string $privatePin = '';
    public string $liftFloorNum = '0';
    public string $name = '0';
    public array $schedule = ['1001'];
    public string $cardCode = '';
    public string $webRelay = '0';
    public string $c4Event = '0';
    public string $priorityCall = '0';
    public string $dialAccount = '0';
    public string $phoneNum = '';
    public string $analogSystem = '0';
    public string $analogNumber = '';
    public string $analogReplace = '';
    public string $analogMode = '0';
    public string $analogProxyAddress = '';
    public string $contactId = '';
    public string $group = 'Default';
    public string $bleAuthCode = '';
    public string $bleKeyId = '-1';
    public string $bleExpired = 'N/A';
    public string $bleStatus = 'Unpaired';
    public string $source = 'Local';
    public string $scheduleRelay = '1001-1;';
    public string $qrCodeUrl = '';

    /**
     * Creates a new `User` instance.
     *
     * @param string $userId Unique user ID.
     * @throws InvalidArgumentException if `$userId` is empty.
     */
    public function __construct(string $userId)
    {
        if (empty($userId)) {
            throw new InvalidArgumentException('User ID cannot be empty');
        }

        $this->userId = $userId;
    }

    protected static function getRequiredField(): string
    {
        return 'UserID';
    }
}
