# RBTAgent controller is intentionally exposed only by the HTTPS virtual host.
location ^~ /rbt-agent/v2/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /opt/rbt/server/rbt-agent.php;
        fastcgi_param SCRIPT_NAME /rbt-agent.php;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
        client_max_body_size 4m;
}
