<?php

    /**
     * backends queue namespace
     */

    namespace backends\queue
    {
        class internal extends queue
        {
            /**
             * @inheritDoc
             */
            function changed($objectType, $objectId)
            {
                // TODO: Implement changed() method.
            }

            /**
             * @inheritDoc
             */
            function addToQueue($objectType, $objectId, $task, $params, $groupId = false)
            {
                // TODO: Implement addToQueue() method.
            }

            /**
             * @inheritDoc
             */
            function cron($part)
            {
                // TODO: Change the autogenerated stub
            }
        }
    }
